//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ElectricMeterEntities : DbContext
    {
        public ElectricMeterEntities()
            : base("name=ElectricMeterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AdminUser> tbl_AdminUser { get; set; }
        public virtual DbSet<tbl_MeterData> tbl_MeterData { get; set; }
        public virtual DbSet<tbl_ParameterMaster> tbl_ParameterMaster { get; set; }
        public virtual DbSet<tbl_MeterMasterRelay> tbl_MeterMasterRelay { get; set; }
        public virtual DbSet<tbl_BLEDemo> tbl_BLEDemo { get; set; }
    
        public virtual ObjectResult<sp_FetchData_Result> sp_FetchData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FetchData_Result>("sp_FetchData");
        }
    }
}
