//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SmartMeter_ProdEntities1 : DbContext
    {
        public SmartMeter_ProdEntities1()
            : base("name=SmartMeter_ProdEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_epsettings> tbl_epsettings { get; set; }
        public virtual DbSet<tbl_ATGLWaACK> tbl_ATGLWaACK { get; set; }
        public virtual DbSet<tbl_FotaFileUpload> tbl_FotaFileUpload { get; set; }
        public virtual DbSet<tbl_EPROMCommand> tbl_EPROMCommand { get; set; }
    
        public virtual ObjectResult<sp_CustomerLogs_Result> sp_CustomerLogs()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CustomerLogs_Result>("sp_CustomerLogs");
        }
    }
}
