//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_epsettings
    {
        public int ID { get; set; }
        public string EventName { get; set; }
        public string ParameterName { get; set; }
        public string NoOfBytes { get; set; }
        public string type { get; set; }
        public string Addr { get; set; }
        public string Remarks { get; set; }
    }
}
