//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MeterMasterRelay
    {
        public int ID { get; set; }
        public string IPAddress { get; set; }
        public string Password { get; set; }
        public string SystemTitle { get; set; }
        public string BlockCipherKey { get; set; }
        public string AuthenticationKey { get; set; }
        public string Authentication { get; set; }
        public string ServerAddres { get; set; }
        public string ClientAddress { get; set; }
        public string InterfaceType { get; set; }
        public string Security { get; set; }
        public string Port { get; set; }
        public string InvocationCounter { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
