//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SGMReg
    {
        public int ID { get; set; }
        public string CustomreID { get; set; }
        public string SmartMeterSerialNumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
