//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_EPROMCommand
    {
        public int ID { get; set; }
        public string CommandHeader { get; set; }
        public string CommandFotter { get; set; }
        public string Address { get; set; }
        public string Length { get; set; }
        public string CommandName { get; set; }
        public string DataType { get; set; }
        public string ArrayType { get; set; }
    }
}
