//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerRaw
    {
        public int ID { get; set; }
        public string Business_Patner { get; set; }
        public string Full_Name { get; set; }
        public string House_No_ { get; set; }
        public string Street { get; set; }
        public string Street_2 { get; set; }
        public string Street_3 { get; set; }
        public string Street_4 { get; set; }
        public string Street_5 { get; set; }
        public string Mobile_Number { get; set; }
        public string Meter_Number { get; set; }
    }
}
