//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SmartMeterEntities : DbContext
    {
        public SmartMeterEntities()
            : base("name=SmartMeterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_RawData_CRC> tbl_RawData_CRC { get; set; }
        public virtual DbSet<tbl_RawDataAPI> tbl_RawDataAPI { get; set; }
        public virtual DbSet<tbl_CustomerDetails> tbl_CustomerDetails { get; set; }
        public virtual DbSet<CustomerRaw> CustomerRaws { get; set; }
        public virtual DbSet<tbl_SerialNumberMaster> tbl_SerialNumberMaster { get; set; }
        public virtual DbSet<tbl_RoleMaster> tbl_RoleMaster { get; set; }
        public virtual DbSet<tbl_AdminCredentials> tbl_AdminCredentials { get; set; }
        public virtual DbSet<tbl_CustomerRegistration> tbl_CustomerRegistration { get; set; }
        public virtual DbSet<V_FetchInductiveData> V_FetchInductiveData { get; set; }
        public virtual DbSet<V_DistinctMeter> V_DistinctMeter { get; set; }
        public virtual DbSet<V_FetchDailyConsumption> V_FetchDailyConsumption { get; set; }
        public virtual DbSet<tbl_MeterMaster> tbl_MeterMaster { get; set; }
        public virtual DbSet<tbl_AMRHistory> tbl_AMRHistory { get; set; }
        public virtual DbSet<tbl_JioLogs> tbl_JioLogs { get; set; }
        public virtual DbSet<tbl_SMeterMaster> tbl_SMeterMaster { get; set; }
        public virtual DbSet<tbl_SignalRMaxID> tbl_SignalRMaxID { get; set; }
    
        public virtual ObjectResult<FetchCRCData_Result> FetchCRCData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchCRCData_Result>("FetchCRCData");
        }
    
        public virtual int sp_Get15DayReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Get15DayReport");
        }
    
        public virtual ObjectResult<FetchConsumption_MagneticTemper_Result> FetchConsumption_MagneticTemper()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_MagneticTemper_Result>("FetchConsumption_MagneticTemper");
        }
    
        public virtual ObjectResult<FetchConsumption_VayudutWise_Result> FetchConsumption_VayudutWise()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_VayudutWise_Result>("FetchConsumption_VayudutWise");
        }
    
        public virtual ObjectResult<sp_ZeroConsumption_Result> sp_ZeroConsumption()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ZeroConsumption_Result>("sp_ZeroConsumption");
        }
    
        public virtual ObjectResult<sp_TotalRevenue_Result> sp_TotalRevenue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalRevenue_Result>("sp_TotalRevenue");
        }
    
        public virtual ObjectResult<sp_ConsumptionGraph_Result> sp_ConsumptionGraph()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ConsumptionGraph_Result>("sp_ConsumptionGraph");
        }
    
        public virtual ObjectResult<sp_TotalAMR_Result> sp_TotalAMR()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TotalAMR_Result>("sp_TotalAMR");
        }
    
        public virtual int FetchDataConsumption(string busninessPartner)
        {
            var busninessPartnerParameter = busninessPartner != null ?
                new ObjectParameter("BusninessPartner", busninessPartner) :
                new ObjectParameter("BusninessPartner", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("FetchDataConsumption", busninessPartnerParameter);
        }
    
        public virtual ObjectResult<FetchConsumption_Result> FetchConsumption()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_Result>("FetchConsumption");
        }
    
        public virtual ObjectResult<sp_AMRHealth_Result> sp_AMRHealth()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_AMRHealth_Result>("sp_AMRHealth");
        }
    
        public virtual ObjectResult<sp_GenerateInvoice_Result> sp_GenerateInvoice()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GenerateInvoice_Result>("sp_GenerateInvoice");
        }
    
        public virtual ObjectResult<FetchConsumption_Demo_Result> FetchConsumption_Demo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_Demo_Result>("FetchConsumption_Demo");
        }
    
        public virtual ObjectResult<FetchConsumption_15DayRevenue_Demo_Result> FetchConsumption_15DayRevenue_Demo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_15DayRevenue_Demo_Result>("FetchConsumption_15DayRevenue_Demo");
        }
    
        public virtual ObjectResult<FetchConsumption_VayudutWise_Demo_Result> FetchConsumption_VayudutWise_Demo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_VayudutWise_Demo_Result>("FetchConsumption_VayudutWise_Demo");
        }
    
        public virtual ObjectResult<FetchConsumption_CaseTemper_Demo_Result> FetchConsumption_CaseTemper_Demo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_CaseTemper_Demo_Result>("FetchConsumption_CaseTemper_Demo");
        }
    
        public virtual ObjectResult<FetchConsumption_CaseTemper_Result> FetchConsumption_CaseTemper()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_CaseTemper_Result>("FetchConsumption_CaseTemper");
        }
    
        public virtual ObjectResult<sp_GenerateInvoiceForOdoo_Result> sp_GenerateInvoiceForOdoo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GenerateInvoiceForOdoo_Result>("sp_GenerateInvoiceForOdoo");
        }
    
        public virtual ObjectResult<sp_GenerateInvoiceForOdooDateWise_Result> sp_GenerateInvoiceForOdooDateWise(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GenerateInvoiceForOdooDateWise_Result>("sp_GenerateInvoiceForOdooDateWise", startDateParameter, endDateParameter);
        }
    
        public virtual ObjectResult<FetchConsumption_POC_Result> FetchConsumption_POC()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_POC_Result>("FetchConsumption_POC");
        }
    
        public virtual ObjectResult<FetchConsumption_15DayRevenue_Result> FetchConsumption_15DayRevenue()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FetchConsumption_15DayRevenue_Result>("FetchConsumption_15DayRevenue");
        }
    }
}
