//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customers
    {
        public int ID { get; set; }
        public string BusinessPatner { get; set; }
        public string ContractAcct { get; set; }
        public string Contract { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HouseNo { get; set; }
        public string Street { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string Street4 { get; set; }
        public string Street5 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string RegStGrp { get; set; }
        public string ConnectionObject { get; set; }
        public string Installation { get; set; }
        public string Premise { get; set; }
        public string DeviceLocation { get; set; }
        public string MeterType { get; set; }
        public string MeterNumber { get; set; }
        public string ManufacturerMeterNumber { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> MoveInDate { get; set; }
        public Nullable<System.DateTime> MoveOutDate { get; set; }
        public Nullable<System.DateTime> MoveInCreatedOn { get; set; }
        public Nullable<System.DateTime> BPReleaseDate { get; set; }
        public Nullable<System.DateTime> DisconnectionDate { get; set; }
        public string DisconnectionType { get; set; }
        public string ServiceRegulator { get; set; }
        public string DRS { get; set; }
        public string BPType { get; set; }
        public string IDType { get; set; }
        public string Plan { get; set; }
        public string MobilNumber { get; set; }
        public string MobilNumber2 { get; set; }
        public string MobilNumber3 { get; set; }
        public string MobilNumber4 { get; set; }
        public string MobilNumber5 { get; set; }
        public string EmailID { get; set; }
        public string EmailID2 { get; set; }
        public string EmailID3 { get; set; }
        public string EmailID4 { get; set; }
        public string EmailID5 { get; set; }
        public string Plant { get; set; }
        public string MeterReadingUnit { get; set; }
        public string BPSubType { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
        public string ScheduleDate { get; set; }
        public string RentalFlag { get; set; }
        public string Installment_Amount { get; set; }
        public string Installment_Numbers { get; set; }
        public string Discount_Amount { get; set; }
        public string Valid_from { get; set; }
        public string valid_to { get; set; }
    }
}
