//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VayudutMaster
    {
        public int ID { get; set; }
        public Nullable<int> VayudutID { get; set; }
        public Nullable<int> VayudutNumber { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Location { get; set; }
        public string IsActive { get; set; }
        public string CreatedBy { get; set; }
    }
}
