//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VayadutMasterDetails
    {
        public int ID { get; set; }
        public string VayadutNo { get; set; }
        public string PcbNo { get; set; }
        public string CardNo { get; set; }
        public string VayadutId { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string SealNo1 { get; set; }
        public string SealNo2 { get; set; }
        public string Area { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TpiName { get; set; }
        public string GatewayStatus { get; set; }
    }
}
