//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AssignSmartMeter
    {
        public int ID { get; set; }
        public Nullable<int> CustomerInstallationID { get; set; }
        public Nullable<int> MeterID { get; set; }
        public string pld { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
