//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RegisteredComplain
    {
        public int ID { get; set; }
        public int TicketTypeID { get; set; }
        public string Complains { get; set; }
        public byte[] Image { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string AssignTo { get; set; }
    
        public virtual tbl_TicketTypeMaster tbl_TicketTypeMaster { get; set; }
    }
}
