//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_VayudutRegistration
    {
        public int ID { get; set; }
        public string VayudutSrNo { get; set; }
        public string VayudutInstalledLocation { get; set; }
        public Nullable<System.DateTime> VayudutInstalledDate { get; set; }
        public string PhoneNumber { get; set; }
        public string IMSI { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
