//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SMeterMaster
    {
        public int ID { get; set; }
        public Nullable<double> MeterID { get; set; }
        public string SimICCID { get; set; }
        public Nullable<double> SimNo { get; set; }
        public Nullable<double> IMSI { get; set; }
        public Nullable<double> IMEI { get; set; }
        public string DeviceName { get; set; }
        public string MUNumber { get; set; }
        public string PLD { get; set; }
        public Nullable<double> PLDLength { get; set; }
        public string VID { get; set; }
        public string SVC { get; set; }
        public string AID { get; set; }
        public string AppName { get; set; }
        public Nullable<double> EID { get; set; }
    }
}
