//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AMRAckData
    {
        public int ID { get; set; }
        public Nullable<int> Installation { get; set; }
        public Nullable<int> Date { get; set; }
        public string Material { get; set; }
        public string Meter_Serial_Number { get; set; }
        public string Message_Type { get; set; }
        public string Message_ID { get; set; }
        public string Message_Description { get; set; }
    }
}
