//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RawDataAPI
    {
        public int ID { get; set; }
        public string VayudutName { get; set; }
        public string ReceptionDate { get; set; }
        public string Time { get; set; }
        public Nullable<int> TXID { get; set; }
        public Nullable<int> DataCount { get; set; }
        public Nullable<decimal> BatteryPower { get; set; }
    }
}
