//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_OTACommands
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Command { get; set; }
        public string Code { get; set; }
        public Nullable<int> StartingPostion { get; set; }
        public Nullable<int> EndingPostion { get; set; }
        public Nullable<int> TimeOut { get; set; }
    }
}
