//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SimCardMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_SimCardMaster()
        {
            this.tbl_VayudutMaster = new HashSet<tbl_VayudutMaster>();
        }
    
        public int ID { get; set; }
        public long SimNumber { get; set; }
        public long MobileNumber { get; set; }
        public string DataPackage { get; set; }
        public System.DateTime BillDate { get; set; }
        public string Issuer { get; set; }
        public string IssuedBy { get; set; }
        public string AssignedTo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_VayudutMaster> tbl_VayudutMaster { get; set; }
    }
}
