//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AMRRegistration
    {
        public int ID { get; set; }
        public byte[] Image { get; set; }
        public int CustomerID { get; set; }
        public int VayudutID { get; set; }
        public int OpeningMeterReading { get; set; }
        public string OpeningAMRReading { get; set; }
        public string SerialNumber { get; set; }
        public string TXID { get; set; }
        public string Altitude { get; set; }
        public string Longitude { get; set; }
        public System.DateTime InstallationDate { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public string ApprovedBy { get; set; }
    
        public virtual tbl_VayudutMaster tbl_VayudutMaster { get; set; }
    }
}
