//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SimCardMaster
    {
        public int ID { get; set; }
        public long SimNumber { get; set; }
        public long MobileNumber { get; set; }
        public string DataPackage { get; set; }
        public System.DateTime BillDate { get; set; }
        public string Issuer { get; set; }
        public string IssuedBy { get; set; }
        public string AssignedTo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
