//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BillingAckData
    {
        public int ID { get; set; }
        public string BusinessPartner { get; set; }
        public string Installation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Material { get; set; }
        public string Meter_SerialNo { get; set; }
        public string MessageType { get; set; }
        public string MessageID { get; set; }
        public string MessageDescription { get; set; }
    }
}
