//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerRegistration
    {
        public int ID { get; set; }
        public string Image { get; set; }
        public Nullable<int> BusinessPartnerNo { get; set; }
        public Nullable<int> MeterNumber { get; set; }
        public Nullable<decimal> OpeningMeterReading { get; set; }
        public Nullable<decimal> OpeningAMRReading { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> TXID { get; set; }
        public string Altitude { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string PinCode { get; set; }
        public string Town { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public string ApprovedBy { get; set; }
    }
}
