//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CustomerDetails
    {
        public int ID { get; set; }
        public string BusinessPartnerNo { get; set; }
        public string ContractAccount { get; set; }
        public string MeterReadingUnit { get; set; }
        public string ConnectionObject { get; set; }
        public string FullName { get; set; }
        public string HouseNumber { get; set; }
        public string Street { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string Street4 { get; set; }
        public string Street5 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string SerialNumber { get; set; }
    }
}
