//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AMRHistory
    {
        public int ID { get; set; }
        public string BusinessPartnerNo { get; set; }
        public string MeterNumber { get; set; }
        public string New_AMR_TXID { get; set; }
        public string Old_AMR_TXID { get; set; }
        public string New_AMR_Serial_Number { get; set; }
        public string Old_AMR_Serial_Number { get; set; }
        public Nullable<double> New_Opening_Meter_Reading { get; set; }
        public Nullable<double> Old_Opening_Meter_Reading { get; set; }
        public Nullable<double> New_Opening_AMR_Reading { get; set; }
        public Nullable<double> Old_Opening_AMR_Reading { get; set; }
        public Nullable<System.DateTime> New_Installation_Date { get; set; }
        public Nullable<System.DateTime> Old_Installation_Date { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
