//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HESMDMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_FetchDailyConsumption
    {
        public int ID { get; set; }
        public string Rnk { get; set; }
        public string Row_ { get; set; }
        public string FullName { get; set; }
        public string MeterNumber { get; set; }
        public string TXID { get; set; }
        public string BusinessPartnerNo { get; set; }
        public string OpeningMeterReading { get; set; }
        public string OpeningAMRReading { get; set; }
        public string DataCount { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string InstallationDate { get; set; }
        public string ReadingCount { get; set; }
        public string AMRSerialNumber { get; set; }
        public string DailyConsumption { get; set; }
    }
}
